/** @format */

const personImages: Record<string, string> = {
  "Ravshanov Normaxmad": "/institutJamoasi/RavshanDomla.png",
  "Axmedov Dilshot Dilmuradovich": "/institutJamoasi/AxmedovDomla.png",
  "Tashtemirova Nadira Nematillayevna": "/institutJamoasi/NodiraTashtemirova.jpg",
  "Azimov Baxtiyor Magrupovich": "/Domlalar/AzimovBaxtiyor.jpg",
  "Bayxanov Islomjon Ilxomjon o'g'li": "/institutJamoasi/Islomaka.png",
  "Boboraximov Baxtiyor Ixtiyorovich": "/institutJamoasi/Boboraximov%20Baxtiyor.png",
  "Fazilov Shavkat Xayrullayevich": "/institutJamoasi/Fazilov%20Shavkat.png",
  "Fozilova Madina Mirxalilovna": "/institutJamoasi/Fozilova%20Madina.png",
  "Isxakova Laviza Fuatovna": "/institutJamoasi/Laviza.jpg",
  "Kadirov Anvarxodja Asatullayevich": "/institutJamoasi/Direktor%20Anvar.png",
  "Kamilov Mirzoyan Mirzaaxmedovich": "/institutJamoasi/Kamilov%20Mirzoyan.png",
  "Kaxarov Shukrullo Sa'dullo o'g'li": "/institutJamoasi/Kaxarov%20Shukrullo.png",
  "Kaxarov Shukrullo Sa’dullo o‘g‘li": "/institutJamoasi/Kaxarov%20Shukrullo.png",
  "Mirzaev Nomaz": "/Domlalar/MirzayevNomaz.png",
  "Mirzayev Nomaz": "/Domlalar/MirzayevNomaz.png",
  "Murodullayev Baxtiyor To'lqin o'g'li": "/institutJamoasi/Murodullayev%20Baxtiyor.png",
  "Murodullayev Baxtiyor To‘lqin o‘g‘li": "/institutJamoasi/Murodullayev%20Baxtiyor.png",
  "Nuraliyev Faxriddin Murodillaevich": "/institutJamoasi/Nuraliyev%20Faxriddin.png",
  "Nuraliyev Faxriddin Murodullayevich": "/institutJamoasi/Nuraliyev%20Faxriddin.png",
  "Nuraliyev Faxriddin Murodillayevich": "/institutJamoasi/Nuraliyev%20Faxriddin.png",
  "Nuriddinov Azizjon Umidjon o'g'li": "/institutJamoasi/AzizNuriddinov.jpg",
  "Sulyukova Larisa Faritovna": "/institutJamoasi/Sulyukova%20Larisa.png",
  "Xamdamov Rustam Xamdamovich": "/Domlalar/XamdamovRustam.png",
  "Hamdamov Rustam Hamdamovich": "/Domlalar/XamdamovRustam.png",
  "Aloev Raxmatillo Djuraevich": "/Daraja%20beruvchi%20ilmiy%20kengash/Aloev%20Raxmatillo%20Djuraevich.png",
  "Djumayozov Umidjon Zafarjonovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Djumayozov%20Umidjon%20Zafarjonovich.png",
  "Eshmatov Baxtiyor Xasanovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Eshmatov%20Baxtiyor%20Xasanovich.jpg",
  "Ignatev Nikolay Aleksandrovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Ignatev%20Nikolay%20Aleksandrovich.png",
  "Ismagilov Ilyas Idrisovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Ismagilov%20Ilyas%20Idrisovich.png",
  "Madraximov Shavkat Fayzullayevich": "/Daraja%20beruvchi%20ilmiy%20kengash/Madraximov%20Shavkat%20Fayzullayevich.png",
  "Imankulov Timur Sakenovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Imankulov%20Timur%20Sakenovich.png",
  "Muxammadiyev Abduvali Shukurovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Muxammadiyev%20Abduvali%20Shukurovich.png",
  "Rustamov Nasim Tulegenovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Rustamov%20Nasim%20Tulegenovich.png",
  "Djumanov Jamoljon Xudaykulovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Djumanov%20Jamoljon%20Xudaykulovich.png",
  "Opanasenko Vladimir Nikolaevich": "/Daraja%20beruvchi%20ilmiy%20kengash/Opanasenko%20Vladimir%20Nikolaevich.png",
  "Sadullayeva Shaxlo Azimbayevna": "/Daraja%20beruvchi%20ilmiy%20kengash/Sadullayeva%20Shaxlo%20Azimbaevna.png",
  "Sadullayeva Shaxlo Azimbaevna": "/Daraja%20beruvchi%20ilmiy%20kengash/Sadullayeva%20Shaxlo%20Azimbaevna.png",
  "Gulyamov Shuxrat Manapovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Gulyamov%20Shuxrat%20Manapovich.png",
  "Tashaev Azat Aripovich": "/Daraja%20beruvchi%20ilmiy%20kengash/Tashaev%20Azat%20Aripovich.png",
  "Urunbaev Erkin": "/Daraja%20beruvchi%20ilmiy%20kengash/Urunbaev%20Erkin.png",
  "Yetmishboyev Shaxzodbek Ma'murjon o'g'li": "/institutJamoasi/Shaxzod.png",
  "Yetmishboyev Shaxzodbek Ma’murjon o‘g‘li": "/institutJamoasi/Shaxzod.png",
};

export function personImageFor(name: string) {
  return personImages[name];
}
