import type { Locale } from "./config";
import { getProductionContent } from "./production-content";

type Translation = { ru: string; en: string };

const entries: Record<string, Translation> = {
  "Loyihalarga qaytish": { ru: "Вернуться к проектам", en: "Back to Projects" },
  "Loyiha tavsifi": { ru: "Описание проекта", en: "Project Description" },
  "Asosiy imkoniyatlar": { ru: "Основные возможности", en: "Key Capabilities" },
  "Muallif": { ru: "Автор", en: "Author" },
  "Loyiha konsepsiyasi, ishlab chiqilishi va amaliy joriy etilishi.": { ru: "Концепция, разработка и практическое внедрение проекта.", en: "Project concept, development, and practical deployment." },
  "Ishlash bosqichlari": { ru: "Этапы работы", en: "Work Stages" },
  "Natijalar": { ru: "Результаты", en: "Outcomes" },
  "Ishtirokchilar": { ru: "Участники", en: "Participants" },
  "Texnologiyalar": { ru: "Технологии", en: "Technologies" },
  "Boshqa loyihalar": { ru: "Другие проекты", en: "Other Projects" },
  "Jamoa": { ru: "Команда", en: "Team" },
  "Mahsulot ortidagi": { ru: "Специалисты, стоящие", en: "The specialists behind" },
  "mutaxassislar.": { ru: "за продуктом.", en: "the product." },
  "Sun'iy intellekt, dasturiy injiniring, ma'lumotlar tahlili va amaliy tadqiqotlarni yagona mahsulotga aylantiradigan jamoa.": { ru: "Команда, объединяющая искусственный интеллект, программную инженерию, анализ данных и прикладные исследования в единый продукт.", en: "A team that brings artificial intelligence, software engineering, data analytics, and applied research together in a unified product." },
  "mutaxassis": { ru: "специалиста", en: "specialists" }, "bo'linma": { ru: "подразделения", en: "departments" },
  "Profilni ko'rish": { ru: "Посмотреть профиль", en: "View Profile" },
  "Bo'linmalar": { ru: "Подразделения", en: "Departments" }, "To'rtta bo'linma,": { ru: "Четыре подразделения,", en: "Four departments," }, "bitta jarayon.": { ru: "единый процесс.", en: "one process." },
  "Jamoaga qaytish": { ru: "Вернуться к команде", en: "Back to Team" },
  "Mutaxassis profili": { ru: "Профиль специалиста", en: "Specialist Profile" },
  "Bo'lim": { ru: "Подразделение", en: "Department" }, "Tashkilot": { ru: "Организация", en: "Organization" }, "Laboratoriya": { ru: "Лаборатория", en: "Laboratory" },
  "Bog'lanish ma'lumotlari": { ru: "Контактные данные", en: "Contact Details" },
  "Mutaxassis haqida": { ru: "О специалисте", en: "About the Specialist" },
  "Asosiy ko'nikmalar": { ru: "Ключевые навыки", en: "Core Skills" },
  "Mas'uliyatlar": { ru: "Обязанности", en: "Responsibilities" },
  "Portfolio yo'nalishlari": { ru: "Направления портфолио", en: "Portfolio Areas" },
  "Ishtirok etgan loyihalar": { ru: "Проекты с участием специалиста", en: "Projects Contributed To" },
  "Loyihani ko'rish": { ru: "Посмотреть проект", en: "View Project" },
  "Boshqa mutaxassislar": { ru: "Другие специалисты", en: "Other Specialists" },
  "Portfolio": { ru: "Портфолио", en: "Portfolio" },
  "Telefon": { ru: "Телефон", en: "Phone" }, "Bog'lanish": { ru: "Связаться", en: "Contact" }, "Yo'nalishlar": { ru: "Направления", en: "Areas" }, "Loyihalar": { ru: "Проекты", en: "Projects" }, "Havolalar": { ru: "Ссылки", en: "Links" },
  "Data Analytics Team": { ru: "Команда анализа данных", en: "Data Analytics Team" }, "Machine Learning Team": { ru: "Команда машинного обучения", en: "Machine Learning Team" }, "Frontend Engineering": { ru: "Frontend-разработка", en: "Frontend Engineering" }, "Backend Engineering": { ru: "Backend-разработка", en: "Backend Engineering" }, "Infrastructure Team": { ru: "Инфраструктурная команда", en: "Infrastructure Team" }, "Testing Group": { ru: "Группа тестирования", en: "Testing Group" }, "AI Research Department": { ru: "Отдел исследований ИИ", en: "AI Research Department" }, "Innovation Lab": { ru: "Инновационная лаборатория", en: "Innovation Lab" },
  "Smart city": { ru: "Умный город", en: "Smart city" }, "Geo analytics": { ru: "Геоаналитика", en: "Geo analytics" }, "Predictive models": { ru: "Прогнозные модели", en: "Predictive models" }, "API integrations": { ru: "Интеграции API", en: "API integrations" }, "Knowledge automation": { ru: "Автоматизация знаний", en: "Knowledge automation" }, "Semantic search": { ru: "Семантический поиск", en: "Semantic search" }, "Embeddings": { ru: "Векторные представления", en: "Embeddings" }, "Access control": { ru: "Контроль доступа", en: "Access control" }, "Event detection": { ru: "Обнаружение событий", en: "Event detection" }, "Alert routing": { ru: "Маршрутизация оповещений", en: "Alert routing" }, "Model monitoring": { ru: "Мониторинг моделей", en: "Model monitoring" }, "Recommendation": { ru: "Рекомендательная система", en: "Recommendation" }, "Geo filters": { ru: "Геофильтры", en: "Geo filters" }, "Search UX": { ru: "UX поиска", en: "Search UX" }, "Market data": { ru: "Рыночные данные", en: "Market data" }, "Time-series": { ru: "Временные ряды", en: "Time series" }, "Anomaly detection": { ru: "Обнаружение аномалий", en: "Anomaly detection" }, "Financial dashboards": { ru: "Финансовые панели", en: "Financial dashboards" }, "Alerts": { ru: "Оповещения", en: "Alerts" }, "Regression": { ru: "Регрессия", en: "Regression" }, "Feature engineering": { ru: "Конструирование признаков", en: "Feature engineering" }, "Model evaluation": { ru: "Оценка модели", en: "Model evaluation" }, "Scenario analysis": { ru: "Сценарный анализ", en: "Scenario analysis" }, "Sensor data": { ru: "Данные датчиков", en: "Sensor data" }, "Risk scoring": { ru: "Оценка риска", en: "Risk scoring" }, "Environmental analytics": { ru: "Экологическая аналитика", en: "Environmental analytics" }, "Reports": { ru: "Отчёты", en: "Reports" }, "Vector search": { ru: "Векторный поиск", en: "Vector search" }, "Document parser": { ru: "Парсер документов", en: "Document parser" }, "Source citations": { ru: "Ссылки на источники", en: "Source citations" },
  "UrbanCity shahar boshqaruvi uchun ma'lumotga asoslangan qaror qabul qilish muhitini yaratadi. Platforma transport, hududiy zichlik, xizmatlar joylashuvi va infratuzilma signallarini birlashtirib, shahar rivojlanishidagi muammoli nuqtalarni erta aniqlashga yordam beradi.": { ru: "UrbanCity создаёт среду принятия решений на основе данных для управления городом. Платформа объединяет данные о транспорте, плотности районов, расположении услуг и сигналы инфраструктуры, помогая заранее выявлять проблемные точки городского развития.", en: "UrbanCity creates a data-driven decision environment for city management. The platform combines transport, area density, service locations, and infrastructure signals to identify urban development issues early." },
  "Hududlar kesimida indikatorlar paneli shakllantiriladi.": { ru: "Формируется панель показателей по районам.", en: "A dashboard of indicators by area is created." }, "Transport va xizmat ko'rsatish oqimlari solishtiriladi.": { ru: "Сопоставляются транспортные потоки и потоки обслуживания.", en: "Transport and service flows are compared." }, "Shahar rejalashtirish uchun risk va imkoniyat zonalari ajratiladi.": { ru: "Выделяются зоны риска и возможностей для городского планирования.", en: "Risk and opportunity zones are identified for urban planning." },
  "indikator turi": { ru: "типов индикаторов", en: "indicator types" }, "monitoring modeli": { ru: "модель мониторинга", en: "monitoring model" }, "xarita integratsiyasi": { ru: "интеграция карты", en: "map integration" },
  "Ma'lumot yig'ish": { ru: "Сбор данных", en: "Data Collection" }, "Hududiy, statistik va operatsion ma'lumotlar bir joyga jamlanadi.": { ru: "Территориальные, статистические и оперативные данные объединяются в одном месте.", en: "Regional, statistical, and operational data are consolidated in one place." }, "AI tahlil": { ru: "Анализ ИИ", en: "AI Analysis" }, "Model muammoli segmentlar, o'zgarishlar va ehtimoliy trendlarni ajratadi.": { ru: "Модель выявляет проблемные сегменты, изменения и вероятные тенденции.", en: "The model identifies problematic segments, changes, and likely trends." }, "Natija paneli": { ru: "Панель результатов", en: "Results Dashboard" }, "Rahbar va mutaxassislar uchun tushunarli dashboard ko'rinishida beriladi.": { ru: "Результаты представлены в понятной руководителям и специалистам панели.", en: "Results are presented in a dashboard that is clear to managers and specialists." },
  "Handex tashkilot ichidagi tarqoq ma'lumotlarni yagona bilim indeksiga aylantiradi. U hujjatlar, jarayon yozuvlari va ichki bilim bazalaridan kerakli kontekstni topib, foydalanuvchiga qisqa, tekshiriladigan va amaliy javob beradi.": { ru: "Handex преобразует разрозненную информацию организации в единый индекс знаний. Он находит нужный контекст в документах, записях процессов и внутренних базах знаний и выдаёт пользователю краткий, проверяемый и практичный ответ.", en: "Handex turns fragmented organizational information into a unified knowledge index. It finds relevant context in documents, process records, and internal knowledge bases and gives users concise, verifiable, actionable answers." },
  "Hujjatlar ichidan kerakli javob tez topiladi.": { ru: "Нужный ответ быстро находится в документах.", en: "The required answer is found quickly in documents." }, "Ichki jarayonlar bo'yicha bilimlar yo'qolib ketmaydi.": { ru: "Знания о внутренних процессах сохраняются.", en: "Knowledge about internal processes is preserved." }, "Xodimlar uchun tezkor maslahat va izohlar shakllanadi.": { ru: "Для сотрудников формируются оперативные рекомендации и пояснения.", en: "Employees receive rapid guidance and explanations." }, "asosiy arxitektura": { ru: "основная архитектура", en: "core architecture" }, "tezroq qidiruv oqimi": { ru: "ускоренный поиск", en: "faster search flow" }, "ruxsat nazorati": { ru: "контроль доступа", en: "access control" },
  "Indekslash": { ru: "Индексирование", en: "Indexing" }, "Hujjatlar bo'laklanadi, semantik indeksga joylanadi.": { ru: "Документы разбиваются на фрагменты и помещаются в семантический индекс.", en: "Documents are chunked and placed in a semantic index." }, "Kontekst tanlash": { ru: "Выбор контекста", en: "Context Selection" }, "Savolga mos manbalar topilib, javob uchun asos bo'ladi.": { ru: "Находятся подходящие к вопросу источники, которые становятся основой ответа.", en: "Sources relevant to the question are found and used as the basis for the answer." }, "Javob va tekshiruv": { ru: "Ответ и проверка", en: "Answer and Verification" }, "Tizim qisqa xulosa va manba kontekstini birga beradi.": { ru: "Система выдаёт краткий вывод вместе с контекстом источника.", en: "The system provides a concise answer together with source context." },
  "Muhofiz AI kuzatuv, hodisa va xavf signallarini tahlil qilib, muhim holatlarni operatorlarga ustuvorlik bo'yicha chiqaradi. Loyiha xavfsizlik, monitoring va resurslarni tezkor yo'naltirish jarayonlarida inson qarorini kuchaytirishga qaratilgan.": { ru: "Muhofiz AI анализирует наблюдения, события и сигналы риска и выводит операторам важные ситуации по приоритету. Проект усиливает решения человека в процессах безопасности, мониторинга и оперативного распределения ресурсов.", en: "Muhofiz AI analyzes surveillance, incident, and risk signals and prioritizes important situations for operators. The project strengthens human decision-making in security, monitoring, and rapid resource allocation." },
  "Hodisalar ustuvorlik bo'yicha saralanadi.": { ru: "События сортируются по приоритету.", en: "Events are sorted by priority." }, "Operator yuklamasi kamayadi.": { ru: "Нагрузка на операторов снижается.", en: "Operator workload is reduced." }, "Monitoring oqimi bo'yicha izchil audit shakllanadi.": { ru: "Формируется последовательный аудит потока мониторинга.", en: "A consistent audit trail is created for the monitoring flow." }, "hodisa aniqlash": { ru: "обнаружение событий", en: "event detection" }, "signal oqimi": { ru: "поток сигналов", en: "signal stream" }, "qaror izi": { ru: "след решения", en: "decision trail" },
  "Signal qabul qilish": { ru: "Приём сигналов", en: "Signal Intake" }, "Monitoring oqimlari va xabarlar yagona tizimga keladi.": { ru: "Потоки мониторинга и сообщения поступают в единую систему.", en: "Monitoring streams and messages enter a unified system." }, "Tasniflash": { ru: "Классификация", en: "Classification" }, "Model hodisa turini va xavf darajasini ajratadi.": { ru: "Модель определяет тип события и уровень риска.", en: "The model identifies the event type and risk level." }, "Operator paneli": { ru: "Панель оператора", en: "Operator Dashboard" }, "Muhim holatlar tezkor ko'rib chiqish uchun chiqariladi.": { ru: "Важные ситуации выводятся для оперативного рассмотрения.", en: "Important situations are surfaced for rapid review." },
  "DomFinder ko'chmas mulk bozoridagi ma'lumotlarni tartiblaydi, obyektlarni joylashuv, narx, infratuzilma va foydalanuvchi ehtiyojlari bo'yicha taqqoslaydi. Tizim tavsiya mexanizmi orqali mos variantlarni tezroq topishga yordam beradi.": { ru: "DomFinder упорядочивает данные рынка недвижимости и сравнивает объекты по расположению, цене, инфраструктуре и потребностям пользователя. Рекомендательный механизм помогает быстрее находить подходящие варианты.", en: "DomFinder organizes real-estate market data and compares properties by location, price, infrastructure, and user needs. Its recommendation engine helps users find suitable options faster." },
  "Obyektlar ko'p omilli baholash asosida saralanadi.": { ru: "Объекты сортируются на основе многофакторной оценки.", en: "Properties are ranked using multi-factor evaluation." }, "Xaridor ehtiyojiga mos variantlar tavsiya qilinadi.": { ru: "Рекомендуются варианты, соответствующие потребностям покупателя.", en: "Options matching the buyer's needs are recommended." }, "Bozor dinamikasi panelda ko'rinadi.": { ru: "Динамика рынка отображается на панели.", en: "Market dynamics are shown on the dashboard." }, "obyekt ko'rinishi": { ru: "обзор объекта", en: "property view" }, "hududiy filter": { ru: "географический фильтр", en: "geographic filter" }, "sinov bosqichi": { ru: "этап испытаний", en: "testing stage" },
  "Bozor ma'lumoti": { ru: "Рыночные данные", en: "Market Data" }, "E'lonlar, narxlar va hududiy kontekst yig'iladi.": { ru: "Собираются объявления, цены и территориальный контекст.", en: "Listings, prices, and geographic context are collected." }, "Moslik modeli": { ru: "Модель соответствия", en: "Matching Model" }, "Foydalanuvchi ehtiyoji asosida tavsiyalar saralanadi.": { ru: "Рекомендации ранжируются на основе потребностей пользователя.", en: "Recommendations are ranked according to user needs." }, "Interaktiv qidiruv": { ru: "Интерактивный поиск", en: "Interactive Search" }, "Xarita, filter va kartalar orqali variantlar ko'riladi.": { ru: "Варианты просматриваются с помощью карты, фильтров и карточек.", en: "Options are explored through a map, filters, and cards." },
  "Coin moliyaviy signallarni kuzatish, anomaliyalarni aniqlash va bozor o'zgarishlarini tushunarli ko'rsatkichlarga aylantirish uchun ishlab chiqilgan. Platforma riskni baholash va tezkor monitoring ssenariylarida ishlatiladi.": { ru: "Coin разработан для отслеживания финансовых сигналов, обнаружения аномалий и преобразования рыночных изменений в понятные показатели. Платформа применяется для оценки рисков и оперативного мониторинга.", en: "Coin is designed to track financial signals, detect anomalies, and turn market changes into clear indicators. The platform is used for risk assessment and rapid monitoring scenarios." },
  "Bozor signallari real vaqtga yaqin kuzatiladi.": { ru: "Рыночные сигналы отслеживаются почти в реальном времени.", en: "Market signals are tracked in near real time." }, "Noan'anaviy o'zgarishlar alohida ajratiladi.": { ru: "Необычные изменения выделяются отдельно.", en: "Unusual changes are highlighted separately." }, "Qaror qabul qilish uchun qisqa risk ko'rsatkichlari beriladi.": { ru: "Для принятия решений предоставляются краткие показатели риска.", en: "Concise risk indicators are provided for decision-making." }, "anomaliya tahlili": { ru: "анализ аномалий", en: "anomaly analysis" },
  "Signal oqimi": { ru: "Поток сигналов", en: "Signal Flow" }, "Ko'rsatkichlar yagona monitoring qatlamiga olinadi.": { ru: "Показатели поступают в единый слой мониторинга.", en: "Indicators are brought into a unified monitoring layer." }, "Risk tahlili": { ru: "Анализ рисков", en: "Risk Analysis" }, "Model odatiy va noodatiy o'zgarishlarni farqlaydi.": { ru: "Модель различает обычные и необычные изменения.", en: "The model distinguishes normal and abnormal changes." }, "Dashboard": { ru: "Панель", en: "Dashboard" }, "Natijalar grafik, jadval va ogohlantirish sifatida ko'rsatiladi.": { ru: "Результаты отображаются в виде графиков, таблиц и предупреждений.", en: "Results are shown as charts, tables, and alerts." },
  "MLR Predictor ko'p omilli regression yondashuvlar yordamida natija ko'rsatkichlarini prognoz qiladi. Loyiha tadqiqot, ishlab chiqarish va boshqaruvdagi sabab-oqibat bog'liqliklarini sinash uchun qulay model muhitini beradi.": { ru: "MLR Predictor прогнозирует итоговые показатели с помощью многофакторных регрессионных подходов. Проект предоставляет удобную модельную среду для проверки причинно-следственных связей в исследованиях, производстве и управлении.", en: "MLR Predictor forecasts outcome indicators using multivariate regression approaches. The project provides a convenient modeling environment for testing cause-and-effect relationships in research, production, and management." },
  "Ko'rsatkichlarga ta'sir qiluvchi omillar aniqlanadi.": { ru: "Определяются факторы, влияющие на показатели.", en: "Factors affecting the indicators are identified." }, "Turli ssenariylar bo'yicha prognozlar olinadi.": { ru: "Получаются прогнозы для различных сценариев.", en: "Forecasts are produced for different scenarios." }, "Model aniqligi testlar orqali baholanadi.": { ru: "Точность модели оценивается с помощью тестов.", en: "Model accuracy is evaluated through tests." }, "model oilasi": { ru: "семейство моделей", en: "model family" }, "ma'lumot kirishi": { ru: "ввод данных", en: "data input" }, "test metrikalari": { ru: "метрики тестирования", en: "test metrics" },
  "Model uchun kerakli o'zgaruvchilar tayyorlanadi.": { ru: "Подготавливаются необходимые для модели переменные.", en: "The variables required by the model are prepared." }, "Trening": { ru: "Обучение", en: "Training" }, "Regression model ma'lumotlar asosida o'qitiladi.": { ru: "Регрессионная модель обучается на данных.", en: "The regression model is trained on the data." }, "Prognoz": { ru: "Прогноз", en: "Forecast" }, "Ssenariylar va metrikalar bilan natija chiqariladi.": { ru: "Результат выводится вместе со сценариями и метриками.", en: "Results are produced with scenarios and metrics." },
  "Ekologik AI Platforma": { ru: "Экологическая платформа ИИ", en: "Environmental AI Platform" }, "Ekologik AI Platforma sensorlar, hududiy ko'rsatkichlar va tarixiy ma'lumotlar asosida ekologik holatni monitoring qiladi. Loyiha risk zonalarini aniqlash, profilaktik choralar va tahliliy hisobotlar tayyorlashni tezlashtiradi.": { ru: "Экологическая платформа ИИ отслеживает состояние окружающей среды на основе данных датчиков, территориальных показателей и исторических данных. Проект ускоряет выявление зон риска, подготовку профилактических мер и аналитических отчётов.", en: "The Environmental AI Platform monitors environmental conditions using sensor data, regional indicators, and historical information. The project accelerates risk-zone detection, preventive measures, and analytical reporting." },
  "Ekologik indikatorlar yagona panelda ko'rinadi.": { ru: "Экологические показатели отображаются на единой панели.", en: "Environmental indicators are shown on a unified dashboard." }, "Riskli hududlar baholash modeli orqali ajratiladi.": { ru: "Зоны риска выделяются с помощью модели оценки.", en: "High-risk areas are identified through an assessment model." }, "Hisobotlar va tavsiyalar tezroq tayyorlanadi.": { ru: "Отчёты и рекомендации готовятся быстрее.", en: "Reports and recommendations are prepared faster." }, "risk indeksi": { ru: "индекс риска", en: "risk index" }, "hududiy qatlam": { ru: "территориальный слой", en: "regional layer" }, "sinov holati": { ru: "статус испытаний", en: "testing status" },
  "Monitoring": { ru: "Мониторинг", en: "Monitoring" }, "Sensor va hududiy ko'rsatkichlar yig'iladi.": { ru: "Собираются данные датчиков и территориальные показатели.", en: "Sensor and regional indicators are collected." }, "AI model ekologik xavf darajasini baholaydi.": { ru: "Модель ИИ оценивает уровень экологического риска.", en: "The AI model assesses the level of environmental risk." }, "Hisobot": { ru: "Отчёт", en: "Report" }, "Mutaxassislar uchun amaliy tavsiyalar shakllanadi.": { ru: "Формируются практические рекомендации для специалистов.", en: "Practical recommendations are prepared for specialists." },
  "RAG Hujjat Tahlili": { ru: "RAG-анализ документов", en: "RAG Document Analysis" }, "RAG Hujjat Tahlili katta hujjat omborlaridan kerakli javobni manba konteksti bilan topadi. Tizim normativ hujjatlar, ichki reglamentlar va ilmiy materiallar bilan ishlaydigan jamoalar uchun bilim qidiruvini soddalashtiradi.": { ru: "RAG-анализ документов находит нужный ответ в больших хранилищах документов вместе с контекстом источника. Система упрощает поиск знаний для команд, работающих с нормативными документами, внутренними регламентами и научными материалами.", en: "RAG Document Analysis finds the required answer in large document repositories together with source context. The system simplifies knowledge retrieval for teams working with regulations, internal policies, and scientific materials." },
  "Javoblar manba konteksti bilan qaytariladi.": { ru: "Ответы возвращаются с контекстом источника.", en: "Answers are returned with source context." }, "Katta hujjatlar tezkor bilim bazasiga aylanadi.": { ru: "Большие документы превращаются в оперативную базу знаний.", en: "Large documents become a readily searchable knowledge base." }, "Mutaxassislar uchun izlash va tekshirish vaqti qisqaradi.": { ru: "Сокращается время поиска и проверки для специалистов.", en: "Search and verification time is reduced for specialists." }, "hujjat tahlili": { ru: "анализ документов", en: "document analysis" }, "savol-javob": { ru: "вопросы и ответы", en: "question answering" },
  "Parsing": { ru: "Разбор", en: "Parsing" }, "Hujjatlar tuzilmasi saqlangan holda qayta ishlanadi.": { ru: "Документы обрабатываются с сохранением структуры.", en: "Documents are processed while preserving their structure." }, "Retrieval": { ru: "Поиск", en: "Retrieval" }, "Savolga mos kontekst semantik qidiruv orqali tanlanadi.": { ru: "Подходящий к вопросу контекст выбирается с помощью семантического поиска.", en: "Context relevant to the question is selected through semantic search." }, "Answering": { ru: "Формирование ответа", en: "Answering" }, "Model javobni qisqa izoh va asos bilan beradi.": { ru: "Модель выдаёт ответ с кратким пояснением и обоснованием.", en: "The model provides an answer with a concise explanation and supporting basis." },
  "PropTech": { ru: "PropTech", en: "PropTech" }, "FinTech analytics": { ru: "FinTech-аналитика", en: "FinTech analytics" }, "Predictive analytics": { ru: "Прогнозная аналитика", en: "Predictive analytics" }, "ClimateTech": { ru: "ClimateTech", en: "ClimateTech" }, "Document intelligence": { ru: "Интеллектуальная обработка документов", en: "Document intelligence" }, "panel": { ru: "панель", en: "dashboard" },
  "Bo'lim boshlig'i": { ru: "Начальник отдела", en: "Head of Department" }, "Bosh mutaxassis": { ru: "Главный специалист", en: "Chief Specialist" }, "Yetakchi mutaxassis": { ru: "Ведущий специалист", en: "Lead Specialist" }, "1-mutaxassis": { ru: "Специалист 1-й категории", en: "Category 1 Specialist" }, "2-mutaxassis": { ru: "Специалист 2-й категории", en: "Category 2 Specialist" },
  "Dasturiy mahsulotlarni ishlab chiqish bo'limi": { ru: "Отдел разработки программных продуктов", en: "Software Product Development Department" }, "Institutning ishlab chiqarish yo'nalishida web platformalar, ichki tizimlar, mobil va integratsion dasturiy mahsulotlarni yaratish bo'yicha ishlaydi.": { ru: "Отдел производственного направления института создаёт веб-платформы, внутренние системы, мобильные и интеграционные программные продукты.", en: "Within the institute's production division, the department develops web platforms, internal systems, mobile products, and integration software." },
  "Ma'lumotlar bazasi": { ru: "Базы данных", en: "Databases" }, "Integratsiya": { ru: "Интеграция", en: "Integration" },
  "Dasturiy mahsulotlarni sinovdan o'tkazish bo'limi": { ru: "Отдел тестирования программных продуктов", en: "Software Product Testing Department" }, "Yaratilgan dasturiy mahsulotlarni funksional, texnik, xavfsizlik va foydalanish qulayligi bo'yicha tekshiradi.": { ru: "Проверяет разработанные программные продукты по функциональности, техническим характеристикам, безопасности и удобству использования.", en: "Tests developed software products for functionality, technical quality, security, and usability." },
  "Manual testing": { ru: "Ручное тестирование", en: "Manual testing" }, "Acceptance": { ru: "Приёмочное тестирование", en: "Acceptance" }, "Bug tracking": { ru: "Отслеживание ошибок", en: "Bug tracking" },
  "Axborot texnologiyalarini joriy qilish va axborot xavfsizligini ta'minlash bo'limi": { ru: "Отдел внедрения информационных технологий и обеспечения информационной безопасности", en: "Information Technology Implementation and Information Security Department" }, "Ishlab chiqilgan yechimlarni ish muhitiga joriy qilish, server va tarmoq infratuzilmasi, monitoring hamda axborot xavfsizligini ta'minlashga mas'ul.": { ru: "Отвечает за внедрение разработанных решений в рабочую среду, серверную и сетевую инфраструктуру, мониторинг и информационную безопасность.", en: "Responsible for deploying developed solutions into operating environments and ensuring server and network infrastructure, monitoring, and information security." },
  "Deployment": { ru: "Внедрение", en: "Deployment" }, "DevOps": { ru: "DevOps", en: "DevOps" }, "Cybersecurity": { ru: "Кибербезопасность", en: "Cybersecurity" },
  "AKT startaplarini qo'llab-quvvatlash bo'limi": { ru: "Отдел поддержки стартапов в сфере ИКТ", en: "ICT Startup Support Department" }, "AKT va sun'iy intellekt yo'nalishidagi startap tashabbuslarini aniqlash, rivojlantirish, prototiplash va pilot loyihalarga tayyorlash bilan shug'ullanadi.": { ru: "Выявляет и развивает стартап-инициативы в сфере ИКТ и искусственного интеллекта, создаёт прототипы и готовит их к пилотным проектам.", en: "Identifies and develops startup initiatives in ICT and artificial intelligence, prototypes them, and prepares them for pilot projects." },
  "Startup": { ru: "Стартап", en: "Startup" }, "Pitch deck": { ru: "Презентация проекта", en: "Pitch deck" }, "Mentorlik": { ru: "Менторство", en: "Mentoring" },
  "Dasturiy mahsulotlarni ishlab chiqish bo'yicha bosh mutaxassis": { ru: "Главный специалист по разработке программных продуктов", en: "Chief Software Product Development Specialist" }, "Ishlab chiqarish jarayonlarida texnik yechimlarni loyihalash, dasturlash va amaliy tizimlarni ishga tushirish bo'yicha ko'p yo'nalishli tajribaga ega.": { ru: "Обладает многопрофильным опытом проектирования технических решений, программирования и запуска прикладных систем в производственных процессах.", en: "Has multidisciplinary experience in designing technical solutions, programming, and launching applied systems in production processes." },
  "Texnik arxitektura": { ru: "Техническая архитектура", en: "Technical architecture" }, "Dasturiy mahsulotlar arxitekturasi va ishlab chiqish yo'nalishini belgilash.": { ru: "Определение архитектуры программных продуктов и направления разработки.", en: "Define software product architecture and development direction." }, "Backend, frontend va integratsiya oqimlarini ishlab chiqish.": { ru: "Разработка backend-, frontend- и интеграционных потоков.", en: "Develop backend, frontend, and integration flows." }, "Murakkab texnik vazifalarni bajarish va jamoa ishini texnik tomondan muvofiqlashtirish.": { ru: "Выполнение сложных технических задач и техническая координация работы команды.", en: "Deliver complex technical tasks and coordinate the team's technical work." },
  "Ishlab chiqarish uchun web platformalar va servislar.": { ru: "Веб-платформы и сервисы для производства.", en: "Web platforms and services for production." }, "Ma'lumot oqimlari va API integratsiyalari.": { ru: "Потоки данных и интеграции API.", en: "Data flows and API integrations." }, "Prototipdan amaliy mahsulotgacha olib borilgan texnik yechimlar.": { ru: "Технические решения, доведённые от прототипа до прикладного продукта.", en: "Technical solutions taken from prototype to applied product." },
  "Dasturiy mahsulotlarni sinovdan o'tkazish va loyiha hujjatlari bo'yicha yetakchi mutaxassis": { ru: "Ведущий специалист по тестированию программных продуктов и проектной документации", en: "Lead Specialist in Software Product Testing and Project Documentation" }, "Loyiha hujjatlari, test ssenariylari, hisobotlar va mahsulot sifatini tartibli nazorat qilish jarayonlariga mas'ul mutaxassis.": { ru: "Специалист, отвечающий за проектную документацию, тестовые сценарии, отчётность и системный контроль качества продукта.", en: "A specialist responsible for project documentation, test scenarios, reporting, and structured product quality control." },
  "QA hujjatlari": { ru: "Документация QA", en: "QA documentation" }, "Test case": { ru: "Тест-кейс", en: "Test case" }, "Bug report": { ru: "Отчёт об ошибке", en: "Bug report" }, "Loyiha nazorati": { ru: "Контроль проекта", en: "Project control" },
  "Test reja, chek-list va qabul qilish mezonlarini hujjatlashtirish.": { ru: "Документирование плана тестирования, чек-листов и критериев приёмки.", en: "Document test plans, checklists, and acceptance criteria." }, "Aniqlangan xatoliklar, topshiriqlar va tuzatishlarni nazorat qilish.": { ru: "Контроль выявленных ошибок, задач и исправлений.", en: "Track identified defects, tasks, and fixes." }, "Jamoa va hamkorlar o'rtasida hujjatli axborot almashinuvini ta'minlash.": { ru: "Обеспечение документированного обмена информацией между командой и партнёрами.", en: "Ensure documented information exchange between the team and partners." },
  "Loyiha pasportlari va ish rejasi shablonlari.": { ru: "Паспорта проектов и шаблоны рабочих планов.", en: "Project charters and work-plan templates." }, "Mahsulot sinovi uchun test ssenariylari.": { ru: "Тестовые сценарии для проверки продукта.", en: "Product testing scenarios." }, "Hamkorlik uchrashuvlari uchun hisobot materiallari.": { ru: "Отчётные материалы для встреч с партнёрами.", en: "Reporting materials for partnership meetings." },
  "AKT startaplarini qo'llab-quvvatlash bo'yicha yetakchi mutaxassis": { ru: "Ведущий специалист по поддержке стартапов в сфере ИКТ", en: "Lead ICT Startup Support Specialist" }, "Startap g'oyalarini qo'llab-quvvatlaydi, jamoani ruhlantiradi va lider sifatida loyihalarning oldinga siljishiga kuch beradi.": { ru: "Поддерживает стартап-идеи, вдохновляет команду и как лидер способствует продвижению проектов.", en: "Supports startup ideas, inspires the team, and provides leadership that moves projects forward." },
  "Startup support": { ru: "Поддержка стартапов", en: "Startup support" }, "Leadership": { ru: "Лидерство", en: "Leadership" }, "Pitch tayyorlash": { ru: "Подготовка презентаций", en: "Pitch preparation" }, "Jamoa koordinatsiyasi": { ru: "Координация команды", en: "Team coordination" }, "Pilot loyiha": { ru: "Пилотный проект", en: "Pilot project" }, "AKT startaplari": { ru: "Стартапы в сфере ИКТ", en: "ICT startups" },
  "Startap tashabbuslarini shakllantirish va rivojlantirishga ko'maklashish.": { ru: "Содействие формированию и развитию стартап-инициатив.", en: "Support the formation and development of startup initiatives." }, "Jamoa ichida motivatsiya, intizom va umumiy yo'nalishni ushlab turish.": { ru: "Поддержание мотивации, дисциплины и общего направления внутри команды.", en: "Maintain motivation, discipline, and shared direction within the team." }, "Loyiha taqdimotlari va tanlovlarga tayyorgarlik jarayonini qo'llab-quvvatlash.": { ru: "Поддержка подготовки проектных презентаций и участия в конкурсах.", en: "Support the preparation of project presentations and competition entries." },
  "Startap g'oyalarini saralash va taqdimotga tayyorlash.": { ru: "Отбор стартап-идей и подготовка к презентации.", en: "Select startup ideas and prepare them for presentation." }, "Jamoaviy ishlarni tashkil qilish va yo'naltirish tajribasi.": { ru: "Опыт организации и координации командной работы.", en: "Experience organizing and guiding teamwork." }, "Tanlov va loyiha jarayonlarida motivatsion liderlik.": { ru: "Мотивационное лидерство в конкурсных и проектных процессах.", en: "Motivational leadership in competitions and project work." },
  "AKT startaplari, mexatronika, robototexnika va 3D prototiplash bo'yicha mutaxassis": { ru: "Специалист по ИКТ-стартапам, мехатронике, робототехнике и 3D-прототипированию", en: "Specialist in ICT Startups, Mechatronics, Robotics, and 3D Prototyping" }, "Bir qancha startap loyihalarida g'olib bo'lgan, mexatronika, robototexnika va 3D printer yo'nalishlarida amaliy qurilmalar bilan ishlaydigan kuchli mutaxassis.": { ru: "Сильный специалист, победитель нескольких стартап-проектов, работающий с практическими устройствами в области мехатроники, робототехники и 3D-печати.", en: "An accomplished specialist and winner of several startup competitions who works with practical devices in mechatronics, robotics, and 3D printing." },
  "Mechatronics": { ru: "Мехатроника", en: "Mechatronics" }, "Robotics": { ru: "Робототехника", en: "Robotics" }, "3D printing": { ru: "3D-печать", en: "3D printing" }, "Startup prototyping": { ru: "Прототипирование стартапов", en: "Startup prototyping" }, "Texnik demo": { ru: "Техническая демонстрация", en: "Technical demo" }, "Robototexnika prototiplari": { ru: "Прототипы робототехники", en: "Robotics prototypes" }, "3D printer ishlanmalari": { ru: "Разработки для 3D-печати", en: "3D printer developments" },
  "Startap g'oyalarini texnik prototipga aylantirish.": { ru: "Преобразование стартап-идей в технические прототипы.", en: "Turn startup ideas into technical prototypes." }, "Mexatronika va robototexnika yo'nalishidagi qurilmalar ustida ishlash.": { ru: "Работа над устройствами в области мехатроники и робототехники.", en: "Work on devices in mechatronics and robotics." }, "3D printer orqali tajriba namunalarini tayyorlash va sinash.": { ru: "Изготовление и тестирование экспериментальных образцов с помощью 3D-принтера.", en: "Produce and test experimental samples using a 3D printer." },
  "Startap tanlovlarida qo'lga kiritilgan yutuqlar.": { ru: "Достижения в стартап-конкурсах.", en: "Achievements in startup competitions." }, "Mexatronik va robototexnik prototiplar.": { ru: "Мехатронные и робототехнические прототипы.", en: "Mechatronic and robotics prototypes." }, "3D printer yordamida tayyorlangan amaliy modellar.": { ru: "Практические модели, изготовленные с помощью 3D-принтера.", en: "Practical models produced with a 3D printer." },
  "Raqamli texnologiyalar va sun'iy intellektni rivojlantirish ilmiy-tadqiqot instituti": { ru: "Научно-исследовательский институт развития цифровых технологий и искусственного интеллекта", en: "Research Institute for the Development of Digital Technologies and Artificial Intelligence" },
};

function findParallelString(source: unknown, target: unknown, value: string): string | undefined {
  if (typeof source === "string") return source === value && typeof target === "string" ? target : undefined;
  if (Array.isArray(source) && Array.isArray(target)) {
    for (let index = 0; index < source.length; index += 1) {
      const found = findParallelString(source[index], target[index], value);
      if (found) return found;
    }
  } else if (source && target && typeof source === "object" && typeof target === "object") {
    for (const key of Object.keys(source as Record<string, unknown>)) {
      const found = findParallelString((source as Record<string, unknown>)[key], (target as Record<string, unknown>)[key], value);
      if (found) return found;
    }
  }
  return undefined;
}

export function localizeProductionInfo<T>(value: T, locale: Locale): T {
  if (locale === "uz") return value;
  if (typeof value === "string") {
    const direct = entries[value]?.[locale];
    if (direct) return direct as T;
    const parallel = findParallelString(getProductionContent("uz"), getProductionContent(locale), value);
    return (parallel ?? value) as T;
  }
  if (Array.isArray(value)) return value.map((item) => localizeProductionInfo(item, locale)) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, localizeProductionInfo(item, locale)])) as T;
  }
  return value;
}
