export type ProjectCopy = {
  title?: string;
  sector?: string;
  shortDescription: string;
  description: string;
  leadDepartment?: string;
  capabilities: string[];
  outcomes: string[];
  metrics: { value: string; label: string }[];
  stages: { title: string; description: string }[];
};

type Translations = { ru: ProjectCopy; en: ProjectCopy };

const copies: Record<string, Translations> = {
  "handex": {
    ru: {
      title: "Handex", sector: "Доступность / ИИ", shortDescription: "Инклюзивная платформа с переводом, словарём жестов и интерактивным обучением для людей с нарушением слуха.",
      description: "Handex расширяет возможности повседневного общения для глухих и слабослышащих людей. Платформа объединяет словарь жестового языка, дактильные инструменты, перевод текста и жестов, визуальный контент и игровые упражнения в едином доступном интерфейсе. Цель проекта — уменьшить коммуникационные барьеры между людьми с нарушением слуха и окружающими.",
      leadDepartment: "Автор и руководитель проекта",
      capabilities: ["Словарь жестового языка", "Перевод текста и жестов", "Дактильные / finger-spelling инструменты", "Интерактивные уроки и визуальный контент", "Квизы и игровые упражнения", "Доступный мобильный и веб-интерфейс"],
      outcomes: ["Помогает уменьшить коммуникационные барьеры.", "Поддерживает обучение через словарь жестов и интерактивные упражнения.", "Занял второе место в конкурсе President Tech Award."],
      metrics: [{ value: "5000+", label: "пользователей" }, { value: "1000+", label: "жестов" }, { value: "2-е место", label: "President Tech Award" }],
      stages: [{ title: "Словарь и перевод", description: "Слова, понятия и тексты связываются с данными жестового языка." }, { title: "Интерактивное обучение", description: "Квизы, игры и визуальный контент помогают закреплять знания." }, { title: "Доступный пользовательский опыт", description: "Мобильные и веб-интерфейсы проектируются понятными для разных групп пользователей." }],
    },
    en: {
      title: "Handex", sector: "Accessibility / AI", shortDescription: "An inclusive platform combining translation, a sign-language dictionary, and interactive learning for people with hearing loss.",
      description: "Handex expands everyday communication opportunities for deaf and hard-of-hearing people. The platform combines a sign-language dictionary, finger-spelling tools, text-to-sign translation, visual content, and game-based exercises in one accessible experience. Its goal is to reduce communication barriers between people with hearing loss and the wider community.",
      leadDepartment: "Author and Project Lead",
      capabilities: ["Sign-language dictionary", "Text and sign translation", "Finger-spelling tools", "Interactive lessons and visual content", "Quizzes and learning games", "Accessible mobile and web interface"],
      outcomes: ["Helps reduce communication barriers.", "Supports learning through a sign-language dictionary and interactive exercises.", "Won second place in the President Tech Award competition."],
      metrics: [{ value: "5000+", label: "users" }, { value: "1000+", label: "signs" }, { value: "2nd place", label: "President Tech Award" }],
      stages: [{ title: "Dictionary and translation", description: "Words, concepts, and texts are connected to sign-language data." }, { title: "Interactive learning", description: "Quizzes, games, and visual content help users reinforce their knowledge." }, { title: "Accessible experience", description: "Mobile and web interfaces are designed to be clear for different user groups." }],
    },
  },
  "urban-city": {
    ru: {
      title: "UrbanCity", sector: "Умный город / ИИ", shortDescription: "Платформа городской аналитики, которая анализирует инфраструктуру, транспортные потоки и развитие районов с помощью ИИ.",
      description: "UrbanCity объединяет данные о городской инфраструктуре, транспортных потоках и развитии территорий и анализирует их с помощью ИИ и data analytics. Платформа помогает принимать решения на основе данных: показатели загруженности, плотности населения, зелёных зон, дорог и территориальных KPI отображаются на единой карте и панели управления.", leadDepartment: "Автор и руководитель проекта",
      capabilities: ["Мониторинг городской инфраструктуры", "Анализ транспортных потоков и пробок", "Сравнение показателей развития районов", "Показатели плотности населения и урбанизации", "Анализ дорог и зелёных зон на карте", "Тренды и прогнозы на основе ИИ"],
      outcomes: ["Инфраструктура и транспортные потоки наблюдаются на единой панели.", "Показатели и KPI сравниваются по районам.", "Прогнозы на основе ИИ поддерживают стратегическое планирование."], metrics: [{ value: "GIS", label: "анализ карт" }, { value: "AI", label: "прогнозирование" }, { value: "KPI", label: "городские показатели" }], stages: [{ title: "Интеграция данных", description: "Транспортные, статистические и операционные данные объединяются в единую модель." }, { title: "Геопространственный анализ", description: "Слои карты, плотности, дорог и зелёных зон используются для анализа города." }, { title: "Прогноз и dashboard", description: "Результаты ИИ выводятся специалистам в виде понятных индикаторов и панели управления." }],
    },
    en: {
      title: "UrbanCity", sector: "Smart City / AI", shortDescription: "An AI-powered urban analytics platform for city infrastructure, traffic flows, and regional development.",
      description: "UrbanCity combines city infrastructure, traffic-flow, and regional-development data for AI-powered analysis. It supports data-driven decisions by bringing congestion, population density, green areas, road networks, and regional KPIs into one map and dashboard.", leadDepartment: "Author and Project Lead",
      capabilities: ["City infrastructure monitoring", "Traffic-flow and congestion analysis", "Comparison of regional development indicators", "Population-density and urban metrics", "Map-based road and green-area analysis", "AI-powered trend and forecasting"],
      outcomes: ["Infrastructure and traffic flows are monitored in one dashboard.", "Indicators and KPIs can be compared by area.", "AI forecasts support strategic urban planning."], metrics: [{ value: "GIS", label: "map analytics" }, { value: "AI", label: "forecasting" }, { value: "KPI", label: "city indicators" }], stages: [{ title: "Data integration", description: "Transport, statistical, regional, and operational data are unified into one model." }, { title: "Geospatial analysis", description: "Map layers for density, roads, and green areas are used to understand the city." }, { title: "Forecast and dashboard", description: "AI results are presented to specialists as clear indicators and a management dashboard." }],
    },
  },
  "muhofiz-ai": {
    ru: {
      title: "Muhofiz AI", sector: "ИИ безопасности", shortDescription: "Система ИИ, которая выявляет сигналы риска и события и помогает ответственным командам быстро принимать решения.", description: "Muhofiz AI выявляет сигналы риска и события из разных каналов мониторинга и помогает ответственным командам принимать быстрые и обоснованные решения. Система не заменяет оператора, а выделяет важные ситуации из большого потока и направляет внимание на приоритетные случаи.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Мониторинг в реальном времени", "Выявление опасных событий", "Расчёт risk score", "Анализ видео, аудио и сенсорных сигналов", "Автоматические оповещения", "Incident dashboard и аналитические отчёты"], outcomes: ["События приоритизируются по уровню риска.", "Видео, аудио, сенсорные и IoT-сигналы объединяются в одном потоке.", "Система усиливает решения оператора и направляет внимание команды на важные ситуации."], metrics: [{ value: "AI", label: "выявление событий" }, { value: "24/7", label: "мониторинг" }, { value: "Risk", label: "приоритизация" }], stages: [{ title: "Приём сигналов", description: "Видео, аудио, сенсорные, сетевые и IoT-потоки поступают в единую систему." }, { title: "Анализ риска", description: "ИИ определяет тип события, уровень риска и приоритет ответа." }, { title: "Быстрый ответ", description: "Оповещения и incident dashboard информируют ответственную команду." }],
    },
    en: {
      title: "Muhofiz AI", sector: "Security AI", shortDescription: "An AI system that detects risk signals and incidents and helps responsible teams make rapid decisions.", description: "Muhofiz AI detects risk signals and incidents from multiple monitoring channels and helps responsible teams make fast, evidence-based decisions. It does not replace the human operator; it filters important situations from large streams and directs attention to high-priority cases.", leadDepartment: "Author and Project Lead", capabilities: ["Real-time monitoring", "Hazardous-incident detection", "Risk-score calculation", "Video, audio, and sensor analysis", "Automated alerts and notifications", "Incident dashboard and analytics reports"], outcomes: ["Incidents are prioritized by risk level.", "Video, audio, sensor, and IoT signals are shown in one monitoring stream.", "The system strengthens operator decisions and focuses the team on important situations."], metrics: [{ value: "AI", label: "incident detection" }, { value: "24/7", label: "monitoring" }, { value: "Risk", label: "prioritization" }], stages: [{ title: "Signal intake", description: "Video, audio, sensor, network, and IoT streams enter one system." }, { title: "Risk analysis", description: "AI identifies the incident type, risk level, and response priority." }, { title: "Rapid response", description: "Alerts and the incident dashboard notify the responsible team." }],
    },
  },
  "mlr-predictor": {
    ru: {
      title: "MLR Predictor", sector: "AgriTech / ML", shortDescription: "AgriTech-платформа, прогнозирующая урожайность по данным о погоде, почве и агрономических показателях с помощью машинного обучения.", description: "MLR Predictor — научно-исследовательский проект периода магистратуры Abdulhakimov Hojiakbar, преобразованный в прикладную программную платформу. Система использует тип культуры, площадь, температуру, осадки, pH и NPK почвы, историческую урожайность и NDVI для прогноза урожая.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Прогноз урожайности", "Расчёт урожая на гектар и общего объёма", "Анализ погоды и параметров почвы", "NDVI и спутниковые данные", "Дрон-съёмка и мониторинг полей", "Оценка точности модели и confidence", "Практические рекомендации фермеру"], outcomes: ["Урожайность прогнозируется на гектар и для общего объёма.", "Анализируются данные поля, карты, NDVI, дрона и погоды.", "Качество модели оценивается по R², MAE, MAPE и RMSE."], metrics: [{ value: "MLR", label: "регрессионная модель" }, { value: "91.6%", label: "примерная точность" }, { value: "Agri", label: "прогноз урожайности" }], stages: [{ title: "Подготовка данных", description: "Погодные, почвенные, полевые и агрономические показатели проходят preprocessing." }, { title: "Обучение модели", description: "Регрессионная модель обучается и оценивается по R², MAE, MAPE и RMSE." }, { title: "Прогноз урожайности", description: "Результаты выводятся в dashboard, на карте и в виде рекомендаций для фермера." }],
    },
    en: {
      title: "MLR Predictor", sector: "AgriTech / ML", shortDescription: "An AgriTech platform that forecasts crop yields from weather, soil, and agronomic data using machine learning.", description: "MLR Predictor began as Abdulhakimov Hojiakbar's master's research project and was developed into an applied software platform. It uses crop type, field area, temperature, rainfall, soil pH and NPK, historical yield, and NDVI data to forecast production.", leadDepartment: "Author and Project Lead", capabilities: ["Yield forecasting", "Per-hectare and total-yield calculation", "Weather and soil-parameter analysis", "NDVI and satellite data", "Drone imagery and field monitoring", "Model accuracy and prediction confidence", "Practical recommendations for farmers"], outcomes: ["Yield is forecast per hectare and for the total harvest.", "Field, map, NDVI, drone, and weather data can be analyzed.", "Model quality is evaluated with R², MAE, MAPE, and RMSE."], metrics: [{ value: "MLR", label: "regression model" }, { value: "91.6%", label: "sample accuracy" }, { value: "Agri", label: "yield forecast" }], stages: [{ title: "Data preparation", description: "Weather, soil, field, and agronomic indicators go through preprocessing." }, { title: "Model training", description: "The regression model is trained and evaluated using R², MAE, MAPE, and RMSE." }, { title: "Yield forecast", description: "Results are shown in a dashboard, on maps, and as practical farmer recommendations." }],
    },
  },
  "eco-ai-platform": {
    ru: {
      title: "Экологическая AI-платформа", sector: "Экологический ИИ", shortDescription: "Платформа, объединяющая экологические показатели, IoT-датчики и территориальные индикаторы для оценки рисков окружающей среды.", description: "Экологическая AI-платформа объединяет показатели окружающей среды, IoT-датчики и территориальные индикаторы в единой информационной системе. Она помогает отслеживать качество воздуха и воды, шум, источники загрязнения и экологические риски с помощью карт, dashboard и AI-аналитики.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Мониторинг качества воздуха и AQI", "Показатели PM2.5, PM10, NO₂, SO₂, CO и O₃", "Контроль качества воды и уровня шума", "Экологическая карта и территориальные риски", "Анализ источников загрязнения", "Автоматические предупреждения и рекомендации"], outcomes: ["Экологические показатели отслеживаются на единой панели.", "Критические зоны и источники загрязнения выделяются на карте.", "Формируются предупреждения, рекомендации и периодические отчёты."], metrics: [{ value: "128", label: "примерных датчиков" }, { value: "AQI", label: "качество воздуха" }, { value: "Real-time", label: "мониторинг" }], stages: [{ title: "Данные датчиков", description: "Показатели воздуха, воды, шума и другие индикаторы собираются почти в реальном времени." }, { title: "Карта и оценка риска", description: "Территориальные слои, тренды и anomaly detection используются для оценки рисков." }, { title: "Предупреждения и отчёты", description: "По критическим ситуациям формируются уведомления, рекомендации и недельные или месячные отчёты." }],
    },
    en: {
      title: "Environmental AI Platform", sector: "Environmental AI", shortDescription: "A platform combining environmental indicators, IoT sensors, and regional metrics to assess ecological risks.", description: "The Environmental AI Platform brings environmental indicators, IoT sensors, and regional metrics into one information system. It helps monitor air and water quality, noise, pollution sources, and ecological risks through maps, dashboards, and AI analytics.", leadDepartment: "Author and Project Lead", capabilities: ["Air-quality and AQI monitoring", "PM2.5, PM10, NO₂, SO₂, CO, and O₃ indicators", "Water-quality and noise monitoring", "Environmental map and regional risk levels", "Pollution-source analysis", "Automated alerts and environmental recommendations"], outcomes: ["Environmental indicators are monitored in one dashboard.", "Critical areas and pollution sources are identified on a map.", "Alerts, recommendations, and periodic reports are generated."], metrics: [{ value: "128", label: "sample sensors" }, { value: "AQI", label: "air quality" }, { value: "Real-time", label: "monitoring" }], stages: [{ title: "Sensor data", description: "Air, water, noise, and other environmental indicators are collected near real time." }, { title: "Map and risk analysis", description: "Regional layers, trends, and anomaly detection are used to assess risks." }, { title: "Alerts and reporting", description: "Critical situations produce alerts, recommendations, and weekly or monthly reports." }],
    },
  },
  "rag-hujjat-tahlili": {
    ru: {
      title: "RAG-анализ документов", sector: "LLM / RAG", shortDescription: "ИИ-помощник на архитектуре RAG для поиска точных ответов в документах, нормативных текстах и внутренних базах знаний.", description: "RAG-анализ документов находит нужную информацию в PDF, DOCX, TXT, нормативных документах и внутренних базах знаний. Через parsing, chunking, embedding и semantic retrieval LLM формирует ответ на основе релевантного контекста и показывает источник.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Загрузка PDF, DOCX и TXT", "Автоматический parsing и indexing", "Semantic search и поиск релевантных фрагментов", "Обобщённый ответ по нескольким документам", "Источники и citation в ответе", "Работа с внутренней базой знаний", "Права пользователей и access control"], outcomes: ["Работает с документами и внутренними регламентами.", "Ответы возвращаются вместе с релевантными фрагментами и источниками.", "Access control помогает защищать внутренние и конфиденциальные документы."], metrics: [{ value: "RAG", label: "архитектура" }, { value: "Docs", label: "анализ документов" }, { value: "Source", label: "обоснованный ответ" }], stages: [{ title: "Ingestion и indexing", description: "Документы проходят parsing, cleaning, chunking и embedding." }, { title: "Semantic retrieval", description: "Контекст, соответствующий вопросу, находится через vector index." }, { title: "Grounded answer", description: "LLM формирует ответ на основе выбранных источников и citation." }],
    },
    en: {
      title: "RAG Document Analysis", sector: "LLM / RAG", shortDescription: "A RAG-based AI assistant for finding accurate answers across large documents, regulatory text, and internal knowledge bases.", description: "RAG Document Analysis finds information in PDF, DOCX, TXT, regulatory documents, and internal knowledge bases. Through parsing, chunking, embeddings, and semantic retrieval, the LLM produces an answer grounded in relevant context and shows its source.", leadDepartment: "Author and Project Lead", capabilities: ["PDF, DOCX, and TXT upload", "Automatic parsing and indexing", "Semantic search for relevant fragments", "Answers synthesized across multiple documents", "Sources and citations in answers", "Internal knowledge-base support", "User permissions and access control"], outcomes: ["Works with documents and internal policies.", "Answers include relevant fragments and source references.", "Access control helps protect internal and confidential documents."], metrics: [{ value: "RAG", label: "architecture" }, { value: "Docs", label: "document analysis" }, { value: "Source", label: "grounded answer" }], stages: [{ title: "Ingestion and indexing", description: "Documents pass through parsing, cleaning, chunking, and embedding." }, { title: "Semantic retrieval", description: "Question-relevant context is retrieved through a vector index." }, { title: "Grounded answer", description: "The LLM forms an answer from selected sources and citations." }],
    },
  },
  "dom-finder": {
    ru: {
      title: "DomFinder", sector: "PropTech / ИИ", shortDescription: "Умная платформа недвижимости с поиском, рекомендациями и защитой от мошенничества для аренды и покупки жилья.", description: "DomFinder упрощает аренду, покупку и размещение объектов недвижимости. Владелец публикует фотографии, описание, цену и локацию, а клиент находит варианты по цене, району, площади и количеству комнат. Рекомендательная система и antifraud помогают сделать выбор безопаснее.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Размещение объявлений об аренде и продаже", "Фильтры по цене, району, площади и комнатам", "Поиск на карте", "Избранное и уведомления о новых объявлениях", "Рекомендации по поведению пользователя", "Верификация объявлений и пользователей", "Antifraud risk score", "Поиск одинаковых или украденных изображений"], outcomes: ["Объекты находятся через фильтры и карту.", "Рекомендации учитывают поиски, просмотры и сохранённые объявления.", "Верификация и antifraud снижают количество подозрительных объявлений."], metrics: [{ value: "AI", label: "рекомендации" }, { value: "Geo", label: "поиск на карте" }, { value: "Anti-fraud", label: "безопасные объявления" }], stages: [{ title: "Размещение объявления", description: "Владелец добавляет фотографию, описание, цену и локацию объекта." }, { title: "Подходящие варианты", description: "Пользователь фильтрует варианты по цене, району, площади и комнатам." }, { title: "Рекомендации и antifraud", description: "Рекомендации и оценка риска помогают сделать более безопасный выбор." }],
    },
    en: {
      title: "DomFinder", sector: "PropTech / AI", shortDescription: "A smart real-estate platform combining property search, recommendations, and anti-fraud for renting and buying homes.", description: "DomFinder simplifies renting, buying, and listing real-estate properties. Owners can publish photos, descriptions, prices, and locations, while clients find options by price, area, size, and number of rooms. Recommendation and anti-fraud mechanisms support safer decisions.", leadDepartment: "Author and Project Lead", capabilities: ["Rental and sales listing creation", "Filters for price, area, size, and rooms", "Map-based search", "Favorites and new-listing notifications", "Behavior-based recommendations", "Listing and user verification", "Anti-fraud risk score", "Duplicate or stolen-image detection"], outcomes: ["Properties can be found through filters and maps.", "Recommendations use searches, views, and saved listings.", "Verification and anti-fraud reduce suspicious listings."], metrics: [{ value: "AI", label: "recommendations" }, { value: "Geo", label: "map search" }, { value: "Anti-fraud", label: "safer listings" }], stages: [{ title: "Listing creation", description: "Owners add the property's image, description, price, and location." }, { title: "Matching options", description: "Users filter properties by price, area, size, and rooms." }, { title: "Recommendations and anti-fraud", description: "Recommendations and risk analysis help users make safer choices." }],
    },
  },
  "coin": {
    ru: {
      title: "Coin", sector: "FinTech / Аналитика", shortDescription: "FinTech-платформа для мониторинга личных и бизнес-финансов, транзакций и рыночных показателей в одном dashboard.", description: "Coin предназначен для мониторинга ежедневных финансовых операций, расходов, поступлений и рыночных показателей в одном dashboard. Система анализирует финансовую историю и формирует рекомендации ИИ по необычным расходам, риску выхода за бюджет и возможностям оптимизации.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Учёт доходов и расходов", "История транзакций и категории расходов", "Карты и кошельки", "Недельные и месячные финансовые отчёты", "Мониторинг валют и рыночных активов", "Контроль бюджета и трендов", "ИИ-рекомендации и поиск необычных расходов", "Мониторинг подозрительных операций"], outcomes: ["Доходы, расходы, транзакции и бюджет видны в одном dashboard.", "Динамика валют и выбранных рыночных активов отслеживается.", "AI-аналитика выявляет необычные расходы и риск выхода за бюджет."], metrics: [{ value: "Live", label: "финансовый мониторинг" }, { value: "AI", label: "рекомендации" }, { value: "BI", label: "аналитическая панель" }], stages: [{ title: "Транзакции", description: "Доходы, расходы, карты, кошельки и категории фиксируются в системе." }, { title: "Аналитика", description: "Анализируются динамика, рыночные показатели и необычные изменения." }, { title: "Рекомендации ИИ", description: "Пользователь получает советы по оптимизации расходов и контролю бюджета." }],
    },
    en: {
      title: "Coin", sector: "FinTech / Analytics", shortDescription: "A fintech analytics platform for monitoring personal and business finances, transactions, and market indicators in one dashboard.", description: "Coin is designed to monitor daily financial operations, expenses, income, and market indicators in one dashboard. It analyzes financial history and provides AI recommendations about unusual spending, budget risks, and opportunities to optimize expenses.", leadDepartment: "Author and Project Lead", capabilities: ["Income and expense tracking", "Transaction history and expense categories", "Cards and wallets", "Weekly and monthly financial reports", "Currency and market-asset monitoring", "Budget control and trends", "AI recommendations and unusual-spend detection", "Suspicious-operation monitoring"], outcomes: ["Income, expenses, transactions, and budget are visible in one dashboard.", "Currency and selected market-asset dynamics can be tracked.", "AI analytics identifies unusual spending and budget-overrun risk."], metrics: [{ value: "Live", label: "financial monitoring" }, { value: "AI", label: "recommendations" }, { value: "BI", label: "analytics dashboard" }], stages: [{ title: "Transactions", description: "Income, expenses, cards, wallets, and categories are recorded." }, { title: "Analytics", description: "Trends, market indicators, and unusual changes are analyzed." }, { title: "AI recommendations", description: "Users receive recommendations for optimizing expenses and controlling their budget." }],
    },
  },
  "mukammal-training": {
    ru: {
      title: "AIRI Training / Mukammal Training", sector: "EdTech / ИИ", shortDescription: "LMS-платформа повышения квалификации преподавателей и специалистов в области ИИ, ML, компьютерного зрения и NLP.", description: "AIRI Training / Mukammal Training — институциональная LMS-платформа, которая обучает искусственному интеллекту через практические курсы и лабораторные задания. Кабинеты студентов, преподавателей и супер-администратора, курсы, прогресс, оценивание, сертификация и AI-чатбот объединены в одной системе. Платформа работает на training.airi.uz.", leadDepartment: "Автор и руководитель проекта", capabilities: ["Кабинеты студента, преподавателя и супер-администратора", "Управление курсами, модулями и уроками", "Видео и лабораторные задания", "Прогресс и оценивание пользователей", "Самостоятельное обучение и сертификация", "Интеграция AI-чатбота", "Фоновые и видеозадачи", "Production-инфраструктура на Docker, Nginx и PostgreSQL"], outcomes: ["Курсы по основам ИИ, ML, компьютерному зрению и NLP объединены в одной системе.", "Видео, лабораторные задания, прогресс, оценивание и сертификация управляются в LMS.", "Production-платформа развёрнута для реальных пользователей."], metrics: [{ value: "500+", label: "преподавателей" }, { value: "20+", label: "специализированных курсов" }, { value: "LMS", label: "production-платформа" }], stages: [{ title: "Курсы и кабинеты", description: "Создаются роли студентов, преподавателей и администраторов, а также структура курсов и уроков." }, { title: "Практическое обучение", description: "Видео, лабораторные задания, самостоятельное обучение и AI-чатбот поддерживают учебный процесс." }, { title: "Прогресс и внедрение", description: "Оценивание, сертификация, фоновые задачи и production deployment обеспечивают стабильную работу." }],
    },
    en: {
      title: "AIRI Training / Mukammal Training", sector: "EdTech / AI", shortDescription: "An LMS platform for upskilling teachers and specialists in AI, machine learning, computer vision, and NLP.", description: "AIRI Training / Mukammal Training is an institutional LMS that teaches artificial intelligence through practical courses and laboratory assignments. Student, teacher, and super-admin workspaces, courses, progress, assessment, certification, and an AI chatbot are unified in one system. The platform is available at training.airi.uz.", leadDepartment: "Author and Project Lead", capabilities: ["Student, teacher, and super-admin workspaces", "Course, module, and lesson management", "Video content and laboratory assignments", "User progress and assessment", "Self-study and certification", "AI chatbot integration", "Background and video processing", "Production infrastructure with Docker, Nginx, and PostgreSQL"], outcomes: ["AI fundamentals, machine learning, computer vision, and NLP courses are unified.", "Video lessons, labs, progress, assessment, and certification are managed in the LMS.", "The production platform is deployed for real users."], metrics: [{ value: "500+", label: "teachers" }, { value: "20+", label: "specialized courses" }, { value: "LMS", label: "production platform" }], stages: [{ title: "Courses and workspaces", description: "Student, teacher, and admin roles and the course-module-lesson structure are established." }, { title: "Practical learning", description: "Video content, laboratory tasks, self-study, and an AI chatbot support the learning process." }, { title: "Progress and deployment", description: "Assessment, certification, background jobs, and production deployment keep the platform reliable." }],
    },
  },
};

export function getProjectCopy(slug: string, locale: "uz" | "ru" | "en") {
  return locale === "uz" ? undefined : copies[slug]?.[locale];
}
